version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: PLANMASTER_MYSQL_DB
    restart: always
    environment:
      MYSQL_DATABASE: planmaster_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  gui_manager:
    image: phpmyadmin/phpmyadmin
    container_name: PLANMASTER_PHPMYADMIN
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8089:80"
    depends_on:
      - database